### ISSUE TITLE
完成CourseService相关功能

### ISSUE THREAD

**Issue by yeiamx** [EducationTraining/ETD_Back#6]
/**
	 * 返回5门最热的课程（按照score排序）
	 * @return
	 */
	ResponseGetCourses getHottestCourses();

	/**
	 * 返回5门最新的课程（按createTime排序）
	 * @return
	 */
	ResponseGetCourses getLatestCourses();

	/**
	 * 获取某一页的课程
	 * @param page
	 * @param limit
	 * @return
	 */
	ResponseGetCourses getCourses(int page, int limit);

	/**
	 * 上传课程图片（实现可仿上传用户头像）
	 * @param file
	 * @param courseId
	 * @param sessionKey 老师sessionKey
	 * @return
	 */
	ResponseUploadAvatar uploadCoursePic(MultipartFile file, Integer courseId, String sessionKey);

	/**
	 * 更新课程信息 注意对startTime的处理
	 * @param request a RequestUpdateCourse Object
	 * @return
	 */
	BaseResponse updateCourseInfo(RequestUpdateCourse request);

**Comment by yeiamx** [comment]
courseservice里前5个方法，还需要写好相应测试。其中有涉及分页查询的功能，我们用的是github.pageHelper.使用方法可参考CourseDAOTest里的相关代码

**Comment by yeiamx** [comment]
因为这些框架代码我写的比较赶，若发现在实现service时有需要新加的dao方法可以自己进行实现，或者有发现代码错误也可以和我讨论。

**Comment by WuJianeng** [comment]
接口还需要修改，现在暂不合并分支。
还有一部分需要测试和修改。

**Comment by WuJianeng** [comment]
相关issue已完成，代码已合并到master分支。
